### ISSUE TITLE
AttributeError: 'Namespace' when running 'checkm coverage'

### ISSUE THREAD

**Issue by Rene-Hoover** [Ecogenomics/CheckM#367]
Hi, 

I ran into the following error message when running 'checkm coverage':

> Unexpected error: <class 'AttributeError'>
> Traceback (most recent call last):
>   File "/usr/local/bin/checkm", line 611, in <module>
>     checkmParser.parseOptions(args)
>   File "/home/rlhoover/.local/lib/python3.7/site-packages/checkm/main.py", line 1013, in parseOptions
>     self.coverage(options)
>   File "/home/rlhoover/.local/lib/python3.7/site-packages/checkm/main.py", line 739, in coverage
>     checkBinInputExists(options.bin_input, False)
> AttributeError: 'Namespace' object has no attribute 'bin_input'

My input was:
`checkm coverage ./fasta_files/no006_C20_25_bins/ ./checkm/checkm_coverage ./BAM_files/no006_C20-25.sort.bam -x fa -t 16 `
 Which worked when I was running v1.1.0, but hasn't since upgrading to v1.2.2. 
 
My files are .fa so I used the -x fa flag. When that didn't work I tried running it on .fna files without the -x flag, but got the same error message.

I double checked my file paths and when I run 'checkm test ~/checkm_test_results' everything passes. I'm not sure what else to try and figured it was time to ask the pros. :)

Thanks for your help!
Cheers,
Rene

**Comment by Rene-Hoover** [comment]
Got it sorted! Something went wrong with my path, but setting it with: 
`PATH=~/.local/bin:$PATH`
before running CheckM resolved the issue.
